formats:
  - extension: abc
    description: "Built-in ABC rules"
    spec:
      prefix: "123"
      suffix: "789"
      validBlockRegex: "^(A[1-9]C)*$"
      errorBlockReplacement: "A255C"
      processorType: "generic"